In [14]:
import numpy as np
import pandas as pd 
import os
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier

In [15]:
# Set hyperparameter values
num_trees = 10
rand_state = 420
num_jobs = 1 # parameter for parallelization

In [16]:
df = pd.read_csv('../bet365_outcome_features.csv', sep=',')
df = df.dropna()

In [50]:
label_colmn = "outcome"
predictor_colmns = ['closing_odds_outcome','home_opening', 'home_closing', 'draw_opening',
       'draw_closing', 'away_opening', 'away_closing',
       'home_opening_minus_closing', 'draw_opening_minus_closing',
       'away_opening_minus_closing', 'home_min', 'home_max', 'home_range',
       'draw_min', 'draw_max', 'draw_range', 'away_min', 'away_max',
       'away_range']
# predictor_colmns = ['closing_odds_outcome']



In [51]:
X = df[predictor_colmns]
y = pd.factorize(df[label_colmn])[0]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=rand_state)

In [27]:
# null_columns=X_train.columns[X_train.isnull().any()]
# print(X_train[X_train.isnull().any(axis=1)][null_columns].head())
# X_train['closing_odds_outcome'][289]
# null_columns
# X_train.isnull().any(axis=1).sum()

In [28]:
null_columns=df.columns[df.isnull().any()]
df[null_columns].isnull().sum()

Series([], dtype: float64)

In [52]:
RF_clf = RandomForestClassifier(n_estimators=num_trees, random_state=rand_state)


In [53]:
RF_clf.fit(X_train, y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=None,
            oob_score=False, random_state=420, verbose=0, warm_start=False)

In [54]:
y_pred = RF_clf.predict(X_test)
y_pred, y_test

(array([0, 0, 0, 0, 0, 1, 0, 1, 2, 0, 0, 1, 1, 1, 1, 0, 1, 2, 2, 0, 1, 0,
        2, 2, 1, 0, 0, 1, 0, 2, 0, 1, 0, 2, 1, 1, 1, 1, 1, 2, 0, 2, 0, 0,
        1, 2, 1, 1, 0, 2, 1, 2, 1, 1, 0, 2, 0, 0, 0, 0, 1, 2, 0, 1, 0, 1,
        1, 1, 1, 1, 1, 0, 2, 0, 0, 0, 0, 0, 1, 0, 2, 0, 1, 1, 2, 0, 0],
       dtype=int64),
 array([0, 0, 0, 0, 0, 1, 0, 1, 2, 0, 0, 1, 1, 1, 1, 0, 1, 2, 2, 0, 1, 0,
        2, 2, 1, 0, 0, 1, 0, 2, 0, 1, 0, 2, 2, 1, 1, 1, 1, 2, 0, 2, 0, 0,
        1, 2, 1, 1, 0, 2, 1, 0, 2, 1, 0, 0, 2, 0, 0, 0, 0, 2, 0, 1, 0, 0,
        1, 1, 1, 1, 1, 0, 2, 0, 0, 0, 0, 2, 1, 0, 2, 0, 2, 1, 2, 0, 0],
       dtype=int64))

In [55]:
sum(y_pred==y_test)/len(y_pred)

feature_importances = pd.DataFrame(RF_clf.feature_importances_,
                                   index = X_train.columns,
                                    columns=['importance']).sort_values('importance',                                                                 ascending=False)
feature_importances


0.896551724137931

importance
closing_odds_outcome          0.444444
home_min                      0.051624
away_max                      0.045705
home_opening                  0.042312
away_opening                  0.040354
home_closing                  0.036531
home_opening_minus_closing    0.034369
away_closing                  0.032153
draw_opening_minus_closing    0.030398
home_max                      0.029607
away_min                      0.028546
away_opening_minus_closing    0.027357
home_range                    0.027078
away_range                    0.025296
draw_range                    0.025208
draw_opening                  0.023177
draw_min                      0.022680
draw_max                      0.017432
draw_closing                  0.015728

In [23]:
os.getcwd()
# df.shape
# df
tmp = df['outcome'].astype('category')
tmp.dtype
df.columns
pd.factorize(y)

'C:\\Users\\Erik\\Desktop\\Eulers-Men-Sports-Betting\\ML_Script'

CategoricalDtype(categories=['away', 'draw', 'home'], ordered=False)

Index(['Unnamed: 0', 'V1', 'match_id', 'match_date', 'match_time', 'outcome',
       'closing_odds_outcome', 'home_opening', 'home_closing', 'draw_opening',
       'draw_closing', 'away_opening', 'away_closing',
       'home_opening_minus_closing', 'draw_opening_minus_closing',
       'away_opening_minus_closing', 'home_min', 'home_max', 'home_range',
       'draw_min', 'draw_max', 'draw_range', 'away_min', 'away_max',
       'away_range'],
      dtype='object')

(array([0, 1, 0, 0, 0, 0, 2, 2, 1, 1, 0, 1, 2, 0, 1, 2, 1, 2, 0, 2, 2, 0,
        1, 1, 0, 2, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 2, 0, 2, 2, 1, 1,
        0, 0, 1, 1, 2, 0, 1, 0, 1, 1, 2, 0, 0, 0, 2, 2, 2, 0, 2, 0, 0, 2,
        2, 1, 0, 2, 1, 0, 2, 2, 0, 0, 1, 2, 0, 1, 2, 1, 0, 0, 1, 1, 1, 1,
        1, 2, 0, 2, 0, 0, 2, 2, 2, 0, 0, 0, 0, 1, 0, 2, 1, 0, 1, 0, 0, 2,
        0, 2, 1, 0, 0, 2, 0, 0, 0, 0, 1, 1, 2, 0, 1, 2, 2, 2, 0, 0, 1, 2,
        1, 0, 0, 2, 0, 0, 0, 2, 1, 2, 0, 1, 1, 0, 1, 2, 0, 2, 2, 1, 1, 2,
        0, 1, 1, 0, 1, 0, 2, 0, 2, 1, 0, 2, 0, 1, 2, 0, 0, 1, 2, 0, 1, 1,
        1, 2, 1, 0, 0, 1, 1, 0, 0, 1, 0, 2, 0, 0, 0, 0, 0, 1, 0, 0, 2, 0,
        1, 0, 0, 0, 1, 0, 1, 2, 2, 1, 0, 2, 1, 0, 1, 1, 2, 2, 0, 2, 0, 0,
        2, 0, 1, 0, 0, 2, 0, 2, 1, 2, 2, 0, 0, 1, 0, 1, 0, 2, 0, 0, 0, 2,
        0, 0, 0, 0, 0, 2, 2, 2, 0, 2, 1, 0, 2, 1, 2, 1, 0, 0, 0, 0, 2, 2,
        1, 0, 1, 2, 0, 1, 1, 0, 0, 1, 1, 2, 2, 2, 0, 1, 1, 0, 0, 2, 0, 0,
        1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 

# Explanation of "bet365_outcome_features.csv"

### Columns:
#### Categorical - Ordinal (i.e., ordered)
None 
#### Categorical - Nominal (i.e., unordered)
1. match_id 
4. outcome = {home, away, draw}

#### Various: Dates, Times
2. match_date
3. match_time

#### Numeric
5. closing_odds_outcome
6. home_opening
7. home_closing
8. draw_opening
9. draw_closing
10. away_opening
11. away_closing
12. home_opening_minus_closing
13. draw_opening_minus_closing
14. away_opening_minus_closing
15. home_min
16. home_max
17. home_range
18. draw_min
19. draw_max
20. draw_range
21. away_min
22. away_max
23. away_range

# Ideas
1. Predict winnings given bet size
2. Predict who will win or lose
2. Classifier that will spit out probabilities of winning

# Steps
1. For given dataset (i.e., csv file), create $X$ matrix with features and $y$ vector with outcomes. This is the one step that is dependent on the dataset. Everything else that follows should be independent of dataset.
2. Split data into train/test split
3. Classify
4. Spit out plots and metrics

# Notes
* **Predictors being used now**: 
* Some ML models (e.g., regression and SVM) are algebraic and thus their input must be numeric. To use these categories must be transformed into numbers

# To Dos
### Model evaluation-wise
1. Compare performance to just choosing favored team
2. Tune model re number of trees and any other parameters
3. How does model perform on those games for which difference in odds is high? Same question for difference in odds being low? 

### Miscellaneous
1. How is variable importance calculated for RFs? See [here](https://towardsdatascience.com/random-forest-in-python-24d0893d51c0)
2. How 